cmake_minimum_required(VERSION 3.20)
project(untitled1)

set(CMAKE_CXX_STANDARD 20)

# Exercício 1
add_executable(SomaDeDoisNumeros src/List01_algorithms/SomaDeDoisNumeros.cpp)

# Exercício 2
add_executable(RemoverDuplicatas src/List01_algorithms/RemoverDuplicatasDeVetorOrdenado.cpp)

# Exercício 3
add_executable(InverterUmaString src/List01_algorithms/InverterUmaString.cpp)


# Exercício 4
add_executable(MoverZeros src/List01_algorithms/MoverZeros.cpp)

# Exercício 5
add_executable(ElementoMajoritario src/List01_algorithms/ElementoMajoritario.cpp)

# Exercício 6
add_executable(AnaVivaAMariana src/List01_algorithms/AnaVivaAMariana.cpp)

# Exercício 7
add_executable(DatasDuvidosas src/List01_algorithms/DatasDuvidosas.cpp)

#Lista 02

# Exercício 1

add_executable(SomaCumulativaDeVetor src/List02_algorithms/SomaCumulativaDeVetor.cpp)

# Exercício 2

add_executable(MelhorMomentoParaComprarEVenderAcoes src/List02_algorithms/MelhorMomentoParaComprarEVenderAcoes.cpp)

# Exercício 3

add_executable(RotacaoDeVetorADireita src/List02_algorithms/RotacaoDeVetorADireita.cpp)

# Exercício 4

add_executable(ProdutoDeVetorExcetoOProprioElemento src/List02_algorithms/ProdutoDeVetorExcetoOProprioElemento.cpp)


